### PR TITLE
Updates for functionality on robot 1

### PR DESCRIPTION
**Pull request by rafibaum**
Bug fix branch for fixing issues on robot 1.

### CODE REVIEW

**Comment by rafibaum** [comment]
Tested and fully working.

**Comment by GarrettBurroughs** [comment]
Since everything in this pr has been implemented, can I close it?

**Comment by GarrettBurroughs** [comment]
Close it*

**Comment by rafibaum** [comment]
Closed. Garrett is correct as everything has been implemented from this PR.

**Pull request closed without merging**
